name: dart_wordlists
description: passphrase word lists and parsing utils
version: 0.2.3
homepage: https://github.com/stevesea/dart_wordlists
authors:
  - steve christensen <adventuresmith.rpg@gmail.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  resource: ">=2.1.5 <3.0.0"
  quiver: '>=2.0.0 <3.0.0'
  convert: ^2.1.1
  memoize: ^2.0.0

dev_dependencies:
  test: ^1.6.3
  mockito: ^3.0.2
  args: ^1.5.1
  dart_collection_sampler: ">=0.6.1"
