name: dart_wordlists
description: Wordlist data for passphrases, and for PGP mnemonic parse/unparse
version: 1.0.2
homepage: https://github.com/stevesea/dart_wordlists
authors:
  - steve christensen <adventuresmith.rpg@gmail.com>

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  resource: ">=2.1.5 <3.0.0"
  quiver: ">=2.0.0 <3.0.0"
  convert: ^2.1.1
  memoize: ^2.0.0

dev_dependencies:
  test: ^1.6.4
  mockito: ^4.1.0
  args: ^1.5.2
  dart_collection_sampler: ">=1.0.7"
