name: dart_wordlists
description: passphrase word lists and parsing utils
version: 0.2.0
homepage: https://github.com/stevesea/dart_wordlists
authors:
  - steve christensen <adventuresmith.rpg@gmail.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  resource: ">=2.1.5 <3.0.0"

dev_dependencies:
  test: ^1.3.4
  mockito: ^3.0.0
  args: ^1.5.0
  dart_collection_sampler: ">=0.5.1"
