name: dart_wordlists
description: passphrase word lists and parsing utils
version: 0.0.1
homepage: https://github.com/stevesea/dart_wordlists
authors:
  - steve christensen <adventuresmith.rpg@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  resource: ">=2.1.2"

dev_dependencies:
  test: ^0.12.0
  dart_collection_sampler: ">=0.3.0"
  args: ">=0.13.4 <2.0.0"
