name: dart_wordlists
description: Wordlist data for passphrases, and for PGP mnemonic parse/unparse
version: 3.0.0
homepage: https://github.com/stevesea/dart_wordlists
repository: https://github.com/stevesea/dart_wordlists

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  resource: ">=2.1.6 <3.0.0"
  quiver: ">=2.1.2 <3.0.0"
  convert: ^2.1.1
  memoize: ^2.0.0

dev_dependencies:
  test: ^1.12.0
  mockito: ^4.1.1
  args: ^1.5.2
  dart_collection_sampler: ">=2.0.1"
